"""'initial'

Revision ID: f371b5b3dcc1
Revises: d7750c53eff0
Create Date: 2024-04-05 13:50:03.960887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f371b5b3dcc1'
down_revision: Union[str, None] = 'd7750c53eff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('finish_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'finish_date')
    # ### end Alembic commands ###
